name: ${oc.env:PWD}/models/Qwen2.5-1.5B-qa-sft-qa-additional
class_name: Qwen2ForCausalLM
tokenizer_class: Qwen2Tokenizer
tokenizer_name: ${oc.env:PWD}/models/Qwen2.5-1.5B-qa-sft-qa-additional
inner_params:
# - model.layers.13.mlp.gate_proj.weight
# - model.layers.13.mlp.up_proj.weight
# - model.layers.13.mlp.down_proj.weight
- model.layers.14.mlp.gate_proj.weight
- model.layers.14.mlp.up_proj.weight
- model.layers.14.mlp.down_proj.weight
- model.layers.15.mlp.gate_proj.weight
- model.layers.15.mlp.up_proj.weight
- model.layers.15.mlp.down_proj.weight
- model.layers.16.mlp.gate_proj.weight
- model.layers.16.mlp.up_proj.weight
- model.layers.16.mlp.down_proj.weight
- model.layers.17.mlp.gate_proj.weight
- model.layers.17.mlp.up_proj.weight
- model.layers.17.mlp.down_proj.weight
- model.layers.18.mlp.gate_proj.weight
- model.layers.18.mlp.up_proj.weight
- model.layers.18.mlp.down_proj.weight
- model.layers.19.mlp.gate_proj.weight
- model.layers.19.mlp.up_proj.weight
- model.layers.19.mlp.down_proj.weight
- model.layers.20.mlp.gate_proj.weight
- model.layers.20.mlp.up_proj.weight
- model.layers.20.mlp.down_proj.weight
- model.layers.21.mlp.gate_proj.weight
- model.layers.21.mlp.up_proj.weight
- model.layers.21.mlp.down_proj.weight
- model.layers.22.mlp.gate_proj.weight
- model.layers.22.mlp.up_proj.weight
- model.layers.22.mlp.down_proj.weight
- model.layers.23.mlp.gate_proj.weight
- model.layers.23.mlp.up_proj.weight
- model.layers.23.mlp.down_proj.weight
- model.layers.24.mlp.gate_proj.weight
- model.layers.24.mlp.up_proj.weight
- model.layers.24.mlp.down_proj.weight
- model.layers.25.mlp.gate_proj.weight
- model.layers.25.mlp.up_proj.weight
- model.layers.25.mlp.down_proj.weight
- model.layers.26.mlp.gate_proj.weight
- model.layers.26.mlp.up_proj.weight
- model.layers.26.mlp.down_proj.weight
- model.layers.27.mlp.gate_proj.weight
- model.layers.27.mlp.up_proj.weight
- model.layers.27.mlp.down_proj.weight


# - model.layers.6.mlp.gate_proj.weight
# - model.layers.6.mlp.up_proj.weight
# - model.layers.6.mlp.down_proj.weight
# - model.layers.7.mlp.gate_proj.weight
# - model.layers.7.mlp.up_proj.weight
# - model.layers.7.mlp.down_proj.weight
# - model.layers.8.mlp.gate_proj.weight
# - model.layers.8.mlp.up_proj.weight
# - model.layers.8.mlp.down_proj.weight
# - model.layers.9.mlp.gate_proj.weight
# - model.layers.9.mlp.up_proj.weight
# - model.layers.9.mlp.down_proj.weight
# - model.layers.10.mlp.gate_proj.weight
# - model.layers.10.mlp.up_proj.weight
# - model.layers.10.mlp.down_proj.weight
# - model.layers.11.mlp.gate_proj.weight
# - model.layers.11.mlp.up_proj.weight
# - model.layers.11.mlp.down_proj.weight
# - model.layers.12.mlp.gate_proj.weight
# - model.layers.12.mlp.up_proj.weight
# - model.layers.12.mlp.down_proj.weight